config/routes.rb
Rails.application.routes.draw do
  # get 'recipe/id' => 'recipes/id'
  # get 'campaigns/:slug' => 'campaigns#show'
  root 'users#index'
  resources :activities
  resources :friendships
  resources :users do
    resources :recipes 
  end
  # resources :recipe
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :recipe
end

app/models/friendship.rb
class Friendship < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	include PublicActivity::Model
  	# binding.pry
  	tracked  owner: Proc.new{ |controller, model| model && model.user }
  	attr_accessor :name 
	belongs_to :user
	has_many :comments , dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
	include PublicActivity::Model
  	# binding.pry
  	tracked  
	has_many :recipes ,dependent: :destroy
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
  	# binding.pry
  	# comment_ids = Recipe.where("post_id IN (#{post_ids})", user_id: @user.id).map(&:id)
  	@activities = PublicActivity::Activity.order("created_at desc").where(owner_id: User.ids, owner_type: "User")

  end

  def edit
  	@activity = PublicActivity::Activity.order("created_at desc").find(params[:id])
  end

  def update
  	@activity = PublicActivity::Activity.order("created_at desc").find(params[:id])
  	# if @activity.update(params[:trackable_type])
  	# 	redirect_to activities_url
  	# end
  end

  def destroy
  	
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def destroy
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def destroy
  end

  def edit
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @allRecipe = @user.recipes.all
  end

  def show
    @user = User.find(params[:user_id])
    @recipe =  Recipe.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @recipe = @user.recipes.new
  end

  def create
    @user = User.find(params[:user_id])
    @recipe = @user.recipes.new(recipe_params)
    if @recipe.save
        redirect_to user_recipes_path(@user,@recipe.id)        
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      redirect_to users_url
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @recipe = @user.recipes.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @recipe = @user.recipes.find(params[:id])
    if @recipe.update_attributes(recipe_params)
      redirect_to  user_recipe_url(@user,@recipe.id)
    end
  end

  def recipe_params
    return params.require(:recipe).permit(:user_id, :recipe_name, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @allUser = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path            
    end
  end

  def show
    @user =  User.find(params[:id]) #PublicActivity::Activity.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to users_url     
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to users_url
    end
  end

  def user_params
    return params.require(:user).permit(:name, :password)
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/index.html.erb
<h1>Activities#index</h1>
<p>Find me in app/views/activities/index.html.erb</p>
<h1> User Detailed Page  </h1>

<style type="text/css">
	.wrapper{
		height:auto;
	}
	.center{
		width:80%;
		margin:0 auto;
	}
	.row{
		display: flex;
		flex-flow:row wrap;
		justify-content:space-around;
		padding:2% 0;
		border-bottom:2px dotted #000;
	}
	.colm{ display:flex;flex-flow:row wrap;justify-content:space-around; width:300px;line-height: 50px;  text-align:center;}
	.colm:nth-child(1){width:70px;}
	.btn-container{
		display:flex;flex-flow:row wrap;justify-content:space-around;
		/*line-height: 30px;*/
	}
	.btn{
		padding:5px 16px;
		/*margin-top:10px;*/
		text-decoration:none;
		font-size:18px;
		font-weight:bold;
		border-radius:8px;
	}
	.btn-success{background:#00a300;color:#fff;}
	.btn-danger{background:#ee1111;color:#fff;}
	.btn-primary{background:#2d89ef;color:#fff;}
</style>

<div class="wrapper">
	<div class="center">
		<div class="row">
			<div class="colm"> <h1> <strong> Id </strong> </h1> </div>
			<div class="colm"> <h1> <strong> User Detailed </strong> </h1> </div>
			<div class="colm"> <h1> <strong> Buttons </strong> </h1> </div>
		</div>
	</div>
</div>

<div class="wrapper">
	<div class="center">
  		<% @activities.each do |activity| %>
			<div class="row">
				<div class="colm"> 
					 <%= activity.id %>  </h1> 
				</div>
				<div class="colm"> 
						<%= link_to activity.owner.name, activity.owner if activity.owner %>
	    				<%= render_activity activity %> 
	    		</div>
				<div class="colm">
				 	
				 	<div class="btn-container">
						<%= link_to "New User" ,new_user_path, class: "btn btn-success" %> 					 		
				 	</div>
				</div>
			</div>
		<% end %>
	</div>
</div>
	  <!-- <div class="activity">
	    
	  </div> -->
<%#= render_activities(@activities) %>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/friendships/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

app/views/friendships/edit.html.erb
<h1>Friendships#edit</h1>
<p>Find me in app/views/friendships/edit.html.erb</p>

app/views/friendships/index.html.erb
<h1>Friendships#index</h1>
<p>Find me in app/views/friendships/index.html.erb</p>

app/views/friendships/new.html.erb
<h1>Friendships#new</h1>
<p>Find me in app/views/friendships/new.html.erb</p>

app/views/friendships/show.html.erb
<h1>Friendships#show</h1>
<p>Find me in app/views/friendships/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticePublicActivity</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/public_activity/recipe/_create.html.erb
<% if activity.trackable %>
		<strong style="font-size:18px;">   has been created by   </strong> <%= link_to activity.trackable.recipe_name, user_recipe_url(activity.trackable.user_id,activity.trackable.id) %> 
		
		<% else %>
				<strong> which has since been removed </strong>
<% end %>

app/views/public_activity/recipe/_destroy.html.erb
<% if activity.trackable %>
		<strong style="font-size:18px;">   has been removed by   </strong> <%= link_to activity.trackable.recipe_name, user_recipe_url(activity.trackable.user_id,activity.trackable.id) %> 
		
	<% else %>
			<strong> which has since been removed </strong>
<% end %>

app/views/public_activity/recipe/_update.html.erb
<% if activity.trackable %>
		<strong style="font-size:18px;">   has been update by   </strong> <%= link_to activity.trackable.recipe_name, user_recipe_url(activity.trackable.user_id,activity.trackable.id) %> 
		
	<% else %>
			<strong> which has since been removed </strong>
<% end %>

app/views/public_activity/user/_create.html.erb
<% if activity.trackable %>
		<strong style="font-size:18px;">   has been created by   </strong> <%= link_to activity.trackable.name, activity.trackable %> 
		
	<% else %>
			<strong> which has since been removed </strong>
<% end %>

app/views/public_activity/user/_destroy.html.erb
<% if activity.trackable %>
		<strong style="font-size:18px;">   has been removed by   </strong> <%= link_to activity.trackable.recipe_name, user_recipe_url(activity.trackable.user_id,activity.trackable.id) %> 
		
	<% else %>
			<strong> which has since been removed </strong> 
<% end %>

app/views/public_activity/user/_update.html.erb
<% if activity.trackable %>
	<div class="colm">
		<strong style="font-size:18px;">   has been update by   </strong> <%= link_to activity.trackable.name, activity.trackable %> 
		
	<% else %>
			<strong> which has since been removed </strong>
	</div>
<% end %>

app/views/recipes/destroy.html.erb
<h1>Recipes#destroy</h1>
<p>Find me in app/views/recipes/destroy.html.erb</p>

app/views/recipes/edit.html.erb
<h1>Recipes#new</h1>
<p>Find me in app/views/recipes/new.html.erb</p>
<%= form_for @recipe, url: params[:action]=="new" ? user_recipes_path(@user) :  user_recipe_path(@user, @recipe) do |f| %>
	<p>
		<%= f.label :User_Id %>
		<strong> <%= @user.id %> </strong> <br>
	</p>
	<p>
		<%= f.label :Recipe_Name %>
		<%= f.text_field :recipe_name %> <br>
	</p>
	<p>
		<%= f.label :description %>
		<%= f.text_field :description %> <br>
	</p>
	<p>
		<%= f.submit params[:action]=="new" ? "Create Recipe": "Update Receipe" %>
	</p>
<% end %>

app/views/recipes/index.html.erb
<h1>Recipes#index</h1>
<p>Find me in app/views/recipes/index.html.erb</p>
<style type="text/css" media="screen">
	.wrapper{
		height:auto;
	}
	.center{
		width:80%;
		margin:0 auto;
	}
	.row{
		display: flex;
		flex-flow:row wrap;
		justify-content:space-around;
		padding:2% 0;
		border-bottom:2px dotted #000;
	}
	.colm{ display:flex;flex-flow:row wrap;justify-content:space-around; width:250px;line-height: 50px; text-align:center;}
	.colm:nth-child(1),.colm:nth-child(2){width:70px;}
	.btn-container{
		display:flex;flex-flow:row wrap;justify-content:space-around;
		line-height: 30px;
	}
	.btn{
		padding:7px 16px;
		margin-top:10px;
		text-decoration:none;
		font-size:18px;
		font-weight:bold;
		border-radius:8px;
	}
	.btn-success{background:#00a300;color:#fff;}
	.btn-danger{background:#ee1111;color:#fff;}
	.btn-primary{background:#2d89ef;color:#fff;}
</style>

<div class="wrapper">
	<div class="center">
		<div class="row">
			<div class="colm"> <strong> Id </strong> </div>
			<div class="colm"> <strong> User Id </strong> </div>
			<div class="colm"> <strong> User Name </strong> </div>
			<div class="colm"> <strong> Recipe Name </strong> </div>
			<div class="colm"> <strong> Description </strong> </div>
			<div class="colm"> <strong> Button </strong> </div>
		</div>
	</div>
</div>
<div class="wrapper">
<% @allRecipe.each do|e| %>
	<div class="center">
		<div class="row">
			<div class="colm"> <%= e.id %> </div>	
			<div class="colm"> <%= e.user.id %> </div>	
			<div class="colm"> <%= e.user.name %> </div>	
			<div class="colm"> <%= e.recipe_name %> </div>	
			<div class="colm"> <%= e.description %> </div>	
			<div class="colm"> 
				<div class="btn-container">	
					<%= link_to "New Recipe Create" ,new_user_recipe_path(e.user_id), class: "btn btn-danger" %> 
				</div>
				<div class="btn-container">
					<%= link_to "New User" ,new_user_path, class: "btn btn-success" %>
				</div>
				<div class="btn-container">
					<%= link_to "Show Activities" ,activities_path, class: "btn btn-primary" %>
				</div>
				<div class="btn-container">
					<%= link_to "Show Recipe" , user_recipe_path(@user,e) , class: "btn btn-primary" %>
				</div>
			</div>
		</div>
	</div>
<% end %>
</div>

app/views/recipes/new.html.erb
<h1>Recipes#new</h1>
<p>Find me in app/views/recipes/new.html.erb</p>
<%= form_for @recipe , url:   user_recipes_path(@user) do|f| %>
	<p>
		<%= f.label :User_Id %>
		<strong> <%= @user.id %> </strong> <br>
	</p>
	<p>
		<%= f.label :Recipe_Name %>
		<%= f.text_field :recipe_name %> <br>
	</p>
	<p>
		<%= f.label :description %>
		<%= f.text_field :description %> <br>
	</p>
	<p>
		<%= f.submit "Create Recipe" %>
	</p>
<% end %>

app/views/recipes/show.html.erb
<h1>Recipes#show</h1>
<p>Find me in app/views/recipes/show.html.erb</p>
<style type="text/css">
	.wrapper{
		height:auto;
	}
	.center{
		width:80%;
		margin:0 auto;
	}
	.row{
		display: flex;
		flex-flow:row wrap;
		justify-content:space-around;
		padding:2% 0;
		border-bottom:2px dotted #000;
	}
	.colm{ display:flex;flex-flow:row wrap;justify-content:space-around; width:200px;line-height: 50px; text-align:center;}
	.colm:nth-child(1),.colm:nth-child(2){width:100px;}
	.btn-container{
		display:flex;flex-flow:row wrap;justify-content:space-around;
		line-height: 30px;
	}
	.btn{
		padding:7px 16px;
		margin-top:10px;
		text-decoration:none;
		font-size:18px;
		font-weight:bold;
		border-radius:8px;
	}
	.btn-success{background:#00a300;color:#fff;}
	.btn-danger{background:#ee1111;color:#fff;}
	.btn-primary{background:#2d89ef;color:#fff;}
</style>

<div class="wrapper">
	<div class="center">
		<div class="row">
			<div class="colm"> <h2> <strong> Id </strong> </h2> </div>
			<div class="colm"> <h2> <strong> User Id </strong> </h2> </div>
			<div class="colm"> <h2> <strong> User Name </strong> </h2> </div>
			<div class="colm"> <h2> <strong> Recipe Name </strong> </h2> </div>
			<div class="colm"> <h2> <strong> Buttons </strong> </h2> </div>
		</div>
	</div>
</div>

<div class="wrapper">
	<div class="center">
			<div class="row">
				<div class="colm"> <%= @recipe.id %> </div>
				<div class="colm"> <%= @recipe.user_id %> </div>
				<div class="colm"> <%= User.find(@recipe.user_id).name %> </div>
				<div class="colm"> <%= @recipe.recipe_name %> </div>
				<div class="colm"> 
					<div class="btn-container">
						<%= link_to "Update", edit_user_recipe_url(@user,@recipe) , class: "btn btn-success" %>
					</div>
					<div class="btn-container">
						<%= link_to "Back",  user_recipes_url(@user) , class: "btn btn-primary" %>
					</div>
					<div class="btn-container">
						<%= link_to "Delete", user_recipe_url(@recipe), method: :delete , class: "btn btn-danger" %>
					</div>
					<div class="btn-container">
						<%= link_to "Show Activity",  activities_url, class: "btn btn-success" %>
					</div>
				</div>
			</div>
	</div>
</div>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>
<%= form_for @user, url: user_url(@user) do|e|%>

	<p>
		<%= e.label 'Id => ' %>
		<%= @user.id %>
	</p>
	<p>
		<%= e.label 'Name => ' %>
		<%= e.text_field :name %>
	</p>
	<p>
		<%= e.submit %>
	</p>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<style type="text/css" media="screen">
	.wrapper{
		height:auto;
	}
	.center{
		width:80%;
		margin:0 auto;
	}
	.row{
		display: flex;
		flex-flow:row wrap;
		justify-content:space-around;
		padding:2% 0;
		border-bottom:2px dotted #000;
	}
	.colm{ display:flex;flex-flow:row wrap;justify-content:space-around; width:300px;line-height: 50px; text-align:center;}
	.btn-container{
		display:flex;flex-flow:row wrap;justify-content:space-around;
		line-height: 30px;
	}
	.btn{
		padding:7px 16px;
		margin-top:10px;
		text-decoration:none;
		font-size:18px;
		font-weight:bold;
		border-radius:8px;
	}
	.btn-success{background:#00a300;color:#fff;}
	.btn-danger{background:#ee1111;color:#fff;}
	.btn-primary{background:#2d89ef;color:#fff;}
</style>
<div class="wrapper">
	<div class="center">
		<div class="row">
			<div class="colm"> <strong> Id </strong> </div>
			<div class="colm"> <strong> Name </strong> </div>
			<div class="colm"> <strong> Button </strong> </div>
		</div>
	</div>
</div>
<div class="wrapper">
	<div class="center">
	<% @allUser.each do|e| %>
		<div class="row">
			<div class="colm"> <%= e.id %> </div>	
			<div class="colm"> <%= e.name %> </div>	
			<div class="colm"> 
				<div class="btn-container">	
					<%= link_to "New Recipe Create" ,new_user_recipe_path(e), class: "btn btn-success" %> 
				</div>
				<div class="btn-container">
					<%= link_to "New User" ,new_user_path, class: "btn btn-danger" %> 
				</div>
				<div class="btn-container">
					<%= link_to "Show User" ,user_path(e), class: "btn btn-primary" %>
				</div>
				<div class="btn-container">
					<%= link_to "Show Activity" ,activities_path , class: "btn btn-success" %>
				</div>
			</div>
		</div>
	<% end %>
	</div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<%= form_for @user , url:  users_path do|f| %>
	<p>
		<%= f.label :Name %>
		<%= f.text_field :name %> <br>
	</p>
	<p>
		<%= f.label :Password %>
		<%= f.password_field :password %> <br>
	</p>
	<p>
		<%= f.submit "Create User" %>
	</p>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<style type="text/css">
	.wrapper{
		height:auto;
	}
	.center{
		width:80%;
		margin:0 auto;
	}
	.row{
		display: flex;
		flex-flow:row wrap;
		justify-content:space-around;
		padding:2% 0;
		border-bottom:2px dotted #000;
	}
	.colm{ display:flex;flex-flow:row wrap;justify-content:space-around; width:200px;line-height: 50px; text-align:center;}
	.btn-container{
		display:flex;flex-flow:row wrap;justify-content:space-around;
		line-height: 30px;
	}
	.btn{
		padding:7px 16px;
		margin-top:10px;
		text-decoration:none;
		font-size:18px;
		font-weight:bold;
		border-radius:8px;
	}
	.btn-success{background:#00a300;color:#fff;}
	.btn-danger{background:#ee1111;color:#fff;}
	.btn-primary{background:#2d89ef;color:#fff;}
</style>
<div class="wrapper">
	<div class="center">
		<div class="row" style="justify-content: flex-start; border:none;">
			<div class="btn-container">
				<%= link_to "New User", new_user_url ,class: "btn btn-success" %>
			</div>
		</div>
	</div>
</div>
<div class="wrapper">
	<div class="center">
		<div class="row">
			<div class="colm"> <h2> <strong> Id </strong> </h2> </div>
			<!-- <div class="colm"> <h2> <strong> User Id </strong> </h2> </div> -->
			<div class="colm"> <h2> <strong> User Name </strong> </h2> </div>
			<!-- <div class="colm"> <h2> <strong> Recipe Name </strong> </h2> </div> -->
			<div class="colm"> <h2> <strong> Buttons </strong> </h2> </div>
		</div>
	</div>
</div>

<div class="wrapper">
	<div class="center">
		<%# @user.each do|e| %>
			<div class="row">
				<div class="colm"> <h3> <%= @user.id %> </h3> </div>
				<div class="colm"> <h3> <%= @user.name %> </h3> </div>
				<div class="colm"> 
					<div class="btn-container">
						<%= link_to "Update", edit_user_url(@user) , class: "btn btn-success" %>
					</div>
					<div class="btn-container">
						<%= link_to "Back", users_url , class: "btn btn-primary" %>						
					</div>
					<div class="btn-container">
						<%= link_to "Delete", user_url(@user), method: :delete , class: "btn btn-danger" %>
					</div>
					<div class="btn-container">
						<%= link_to "New Recipe Bno", new_user_recipe_url(@user), class: "btn btn-success" %>
					</div>
				</div>
			</div>
		<%# end %>
	</div>
</div>